# See https://redoc.ly/docs/cli/configuration/ for more information.
apis:
  main@v1:
    root: ./openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: error
features.openapi:
  pagination: none
  showConsole: true
  hideInfoSection: true