# See https://redoc.ly/docs/cli/configuration/ for more information.
lint:
  extends:
    - recommended
  rules:
    no-unused-components: error
features.openapi:
  pagination: none
  showConsole: true
  hideInfoSection: true