meta:
  title: Paper Open API
  description: The best API documentation generator ever.
  siteUrl: https://developer-portal-starter.redoc.ly
  keywords: redocly developer portal, api portal starter, api reference docs
  lang: en-US
linkChecker:
  severity: warning
  options:
    CheckExternal: false
logo:
  image: https://fintech.id/storage/files/shares/logo/logofi2/paperid.png
  altText: Paper logo
toc:
  enable: true
oasDefinitions:
  partners: ./openapi/partners.yaml
  purchase-orders: ./openapi/purchase-orders.yaml
  # add links to definitions in our API registry by using a fully qualified URL.
stylesheets:
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap
  - https://fonts.googleapis.com/css?family=Source+Code+Pro:300,400,600,700&display=swap
#analytics:
  # ga:
  # note that GA doesn't work in the development environment
  #  trackingId: UA-45997213-1
#scripts:
#  - ./static/intercom.js
nav:

  - label: Paper.id Open API Spec
    page: developer-portal/introduction.md

  # - search: true

footer:
  copyrightText: Copyright © Paper.id (PT Pakar Digital Global) 2022-2023. All right reserved.
#   columns:
#     - group: Legal
#       items:
#         - label: Terms of Use
#           href: 'https://redoc.ly/subscription-agreement/'
#         - label: Privacy Notice
#           href: 'https://redoc.ly/privacy-notice/'
#         - label: Cookie Notice
#           href: 'https://redoc.ly/cookie-notice/'
#     - group: Support
#       items:
#         - label: FAQ
#           page: faq.md
#         - label: Contact us
#           page: contact.mdx
