openapi: 3.0.2
info:
  version: 1.0.0
  title: PAPER ID - OPEN API - Tools V1
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://fintech.id/storage/files/shares/logo/logofi2/paperid.png'
externalDocs:
  description: Please registry here first if you don't have access
  url: 'https://paper.id/webappv1/#/login?entry_point=landing-page'
servers:
  - url: 'https://open-api.devel.paper.id/api/v1'
tags: 
  - name: User & Company Account
    description: >
      A company is an entity that represents your company.


      User account can be registered under a Company with an email. A User is an entity that represents a person in your company who will be interacting with the Paper.id system. You can register your first User with our API and add or update users via our Dashboard.
paths:
  '/open-api/register':
    $ref: paths/user/register-user.yaml
components:
  securitySchemes:
    client_id:
      type: apiKey
      in: header
      name: client_id
    client_secret:
      type: apiKey
      in: header
      name: client_secret
    company_id:
      type: apiKey
      in: header
      name: company_id
